### ISSUE TITLE
release tagged versions

### ISSUE THREAD

**Issue by wernerkrauss** [Martimiz/silverstripe-languageprefix#20]
Could you please release tagged versions, so we can include them better in composer?

using "dev-master" just feels bad and is not safe to upgrade.

**Comment by NobrainerWeb** [comment]
+1

**Comment by Martimiz** [comment]
I agree, I just hadn't looked into the howto yet. I'll have a read, and see what the best way is.

(Sorry for the late response Werner, I somehow missed this one)

**Comment by wernerkrauss** [comment]
oh, it's pretty simple:

```
git tag 0.1.0
git push && git push --tags
```

then packagist should get the versions automatically if you set up the packagist hook.,

**Comment by Martimiz** [comment]
Hi Werner, thanks for the input an sorry for the late reply!

It's not that I'm not interested, but because of some fysical issues I'm currently limited to doing only what's absolutely necessary. I'll get back to this as soon as I can.

**Comment by Martimiz** [comment]
Sorry for the endless delay :(

The current version has now moved to a separate branch and is tagged/released as v2.0.0

Master will be updated soon (after some testing) to the new version a substantial rewrite based on the temporary no-prefix-for-default branch. It will (or should) be fully backwards compatible with the current 2.0

**Comment by Martimiz** [comment]
The new version is now released as v3.0.0
