### ISSUE TITLE
Silverstripe 4 Namespacing & Compatibility

### ISSUE THREAD

**Issue by mspacemedia** [Martimiz/silverstripe-languageprefix#32]
Is this module likely to receive an update to make it compatible with SS4?

**Comment by Martimiz** [comment]
Afaik the Translatable module has been abandoned in favor of Fluent for SS4+ So I don’t think there’s any use for it. Or is there?

**Comment by mspacemedia** [comment]
I guess as I have a legacy site that makes use of Translatable that needs to switch to SS4 in the near future. Would you suggest switching that to Fluent?

**Comment by Martimiz** [comment]
I think you should probably... they might even have some upgrade task, I don’t really know

**Comment by mspacemedia** [comment]
This then: https://github.com/tractorcow-farm/silverstripe-fluent/blob/master/docs/en/migrating-from-translatable.md
👍

**Comment by Martimiz** [comment]
Yep that should be it! Thanks 🙂
